### ISSUE TITLE
NoMethodError: undefined method 'assets'

### ISSUE THREAD

**Issue by picman** [easyredmine/redmine_extensions#5]
Redmine 4.1
```
NoMethodError: undefined method 'assets' for #<Rails::Engine::Configuration:0x0000562870c52f80>
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/var/lib/gems/2.5.0/gems/redmine_extensions-0.3.8/lib/redmine_extensions/engine.rb:23:in `block in <class:Engine>'
```

**Comment by ataraxus** [comment]
this one hit me too.. cant upgrade redmine 4.0.6 . to 4.1.0

**Comment by ataraxus** [comment]
apparently something in rails sprockets changed. now one has to add `require 'sprockets/railtie'`to `engine.rb` then sprockets complains about missing *manifest.js` in a more sane way, but i have no clue what to do next, since i dont undestand rails nor ruby.. 

my hack was to comment out lines: 22 -29 apparently my extensions work regardless. but this will break something in the end i think. i just cant see how and what it will break. 

it seems this change will need a new version of this gem

**Comment by luk4s** [comment]
If I remember correctly this issue was fixed by redmine - updated sprockets.
Current version 0.4.5 of this gem is tested with latest Redmine 4.2.x and working.
